openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /facts:
    post:
      summary: Fetch a random fact and shorten the URL
      description: Fetches a random fact from the Useless Facts API, stores it, and returns it.
      responses:
        '200':
          description: Successfully fetched and stored fact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fact'
    get:
      summary: Return all cached facts
      description: Returns all cached facts without incrementing the access count.
      responses:
        '200':
          description: List of all cached facts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fact'
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of facts to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of facts to return

  /facts/{shortenedUrl}:
    get:
      summary: Return a single cached fact
      description: Returns the cached fact and increments the access count.
      parameters:
        - in: path
          name: shortenedUrl
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cached fact retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fact'
        '404':
          description: Fact not found

  /admin/statistics:
    get:
      summary: Access statistics
      description: Provides access statistics for all cached facts.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Access statistics retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FactStats'
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of stats to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of stats to return
        - in: query
          name: order
          schema:
            type: string
            enum:
              - ASC
              - DESC
          description: Sorting order

components:
  schemas:
    Fact:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        source:
          type: string
        source_url:
          type: string
          format: uri
        language:
          type: string
        permalink:
          type: string
          format: uri
        shortUrl:
          type: string
          format: uri

    FactStats:
      type: object
      properties:
        fact:
          $ref: '#/components/schemas/Fact'
        access_count:
          type: integer
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
