ktor:
    application:
        modules:
            - com.challenge.ApplicationKt.module
    deployment:
        port: 8080
    development: true
    environment: "$ENVIRONMENT:local"
    config:
        local:
            baseUrl: "http://0.0.0.0:8080"
            logLevel: "INFO"
